# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex

# docker run --rm -it -v $PWD:/doc aergus/latex sh -c "cd /doc && pdflatex -interaction batchmode document.tex"

image: aergus/latex

build:
  script:
    - pdflatex -interaction batchmode document.tex
    - pdflatex -interaction batchmode document.tex
  artifacts:
    paths:
      - "*.pdf"
